### ISSUE TITLE
Chromium could not be found in Docker and on the demo page

### ISSUE THREAD

**Issue by geek-at** [Lissy93/web-check#95] opened 2024-03-01 09:57 UTC
Hello! Thanks for this amazing repo, it comes in handy for me 😁

Sadly `tech-stack` and `screenshot` jobs are failing because they can't start the browser.

I have seen that in the past ( #43 ) this was an issue but should have been mitigated.

For some reason it still doesn't work for me and seemingly also not for the demo site https://web-check.xyz/

The error is the same in both:

my docker container:
![image](https://github.com/Lissy93/web-check/assets/2073090/28470f9b-97b8-4568-b453-9a5321d5d2c9)

and on web-check.xyz:
![image](https://github.com/Lissy93/web-check/assets/2073090/7b1652df-9e7b-4678-9cd1-e94ad27572bc)

I have checked the Dockerfile and chromium is installed at the correct location so I'm wondering where this bug might come from

**Comment by geek-at** [comment] 2024-03-01 10:07
I have also seen the branch `FIX/chromium-docker` but this also causes errors, although different ones

![image](https://github.com/Lissy93/web-check/assets/2073090/26217056-e775-4ee4-836b-b2e3a868fcc3)

**Comment by stijnos1991** [comment] 2024-03-04 08:31
I'm getting the same errors...

**Comment by Lissy93** [comment] 2024-03-04 14:24
Duplicate of #50

The demo is hosted on Vercel, and Chromium isn't availible to the Vercel lambda functions.

You'll need to run your own instance if you want those checks.

**Closed by Lissy93** 2024-03-04 14:24 UTC

**Comment by geek-at** [comment] 2024-03-04 21:15
Sorry for the confusion I tested the _local_ docker container, not on vercel. On my container there's chromium installed. I have tested from the dockerhub image and built it myself.

Can you confirm that if you run it from docker that the chromium related tests work for you @Lissy93

**Comment by Lissy93** [comment] 2024-03-06 00:26
Ah, sorry I misunderstood. Chromium _should_ work in Docker (it does for me on Arch running amd64 img), but I've found it to be temperamental. It might be worth looking into a different base image, one with a proper Chromium baked in.
